#!/bin/zsh

escseq=$(printf '\033[')

sgr0="${escseq}39;49;00m"
bla="${escseq}30;01m"
red="${escseq}31;01m"
gre="${escseq}32;01m"
yel="${escseq}33;01m"
blu="${escseq}34;01m"
mag="${escseq}35;01m"
cya="${escseq}36;01m"
whi="${escseq}37;01m"

hl1="${yel}"
hl2="${sgr0}"

SQL_QUERY="
WITH RECURSIVE
  get_path(rank, onode, pinode, name, snip) AS (
    SELECT fts.rank, n.inode AS onode, n.pinode, n.name,
      highlight(fts, 1, '${hl1}', '${hl2}') AS snip
    FROM fts
    INNER JOIN iNodes n ON fts.row = n.rowid
    WHERE fts.name MATCH '%s'
    UNION ALL

    SELECT n.rank, n.onode AS onode, pn.pinode, pn.name || '/' ||
 n.name, n.snip AS snip
    FROM get_path n
    INNER JOIN iNodes pn ON n.pinode = pn.inode
)
SELECT
  p.onode,
  p.snip,
  p.name
FROM get_path p
WHERE p.pinode IS NULL
ORDER BY rank
;"

DB_PATH="${1}"
QUERY=$(printf '%s' "${2}" | sed -e 's/^[. /]\+//' -e 's/[. /]\+$//' -e 's/[ ./]/ AND /g')

rffile() {
	(
	  printf '.mode column\n'
	  printf "${SQL_QUERY}" "${2}"
        ) | sqlite3 "${1}"
		#cat
}

rffile "${DB_PATH}" "${QUERY}" \
	| ifne fzf \
		--ansi \
		--multi \
		--cycle \
		--reverse \
		--header-lines=2
